name: "📦 Publish"

on:
  push:
    branches:
      - "releases"

jobs:
  tag:
    name: "Tag"
    permissions:
      contents: "write"
    uses: "kurtmckee/github-workflows/.github/workflows/create-tag-and-release.yaml@598fc01db95578db9417cde9338ae7e7d891e66b" # v2.1

  build:
    name: "Build"
    needs:
      - "tag"
    permissions:
      contents: "read"
    uses: "kurtmckee/github-workflows/.github/workflows/build-python-package.yaml@598fc01db95578db9417cde9338ae7e7d891e66b" # v2.1

  publish:
    name: "Publish"
    needs:
      - "build"
    runs-on: "ubuntu-24.04"
    environment: "PyPI"
    permissions:
      id-token: "write"
    steps:
      - name: "Download the built packages"
        uses: "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c" # v8.0.1
        with:
          artifact-ids: "${{ needs.build.outputs.artifact-id }}"
          path: "${{ needs.build.outputs.packages-path }}"

      - name: "Publish package distributions to PyPI"
        uses: "pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b" # v1.14.0
        with:
          packages-dir: "${{ needs.build.outputs.packages-path }}"
